run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  disable:
    - exhaustive
    - wrapcheck

linters-settings:
  gocritic:
    enabled-checks:
      - dupImport
      - ifElseChain
      - nestingReduce
      - truncateCmp
      - underef
      - unnamedResult

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
